modul_crud_frontend:
    resource: "@modulCRUDFrontendBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

modulCRUDFrontendBundle:
    resource: "@modulCRUDFrontendBundle/Controller/"
    type:     annotation
