security:

    providers:
        in_memory:
            memory: ~

#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
#            security: false
        
#    Sintak Untuk Login        
    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
        main:
            anonymous: ~
