modulCRUD\Bundle\FrontendBundle\Entity\business_partner:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
